EquissentialHorses/src/java/za/co/equissential/util/SystemBean.java
package za.co.equissential.util;

import java.io.Serializable;
import java.util.List;
import java.util.stream.Collectors;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import za.co.equissential.person.entity.Person;
import za.co.equissential.organisation.OrganisationMembership;
import za.co.equissential.organisation.OrganisationRole;
import za.co.equissential.util.SessionUtil;

@Named
@SessionScoped
public class SystemBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private boolean adminAllowed = false;

    private boolean systemAdminAllowed = false;
    
    private SystemMode systemMode;

    private String theme = "blue";

    private List<OrganisationMembership> organisationsToAdmin;

    private OrganisationMembership selectedOrganisationPerson;

    public SystemBean() {
    }

    public void init() {
        if (FacesContext.getCurrentInstance().getExternalContext().isUserInRole("EMMAAdmin")) {
            adminAllowed = true;
        }
        if (FacesContext.getCurrentInstance().getExternalContext().isUserInRole("EMMASystemAdmin")) {
            systemAdminAllowed = true;
        }
        setUserMode();
        getOrganisationsToAdmin(SessionUtil.getLoggedInUser());
        if (organisationsToAdmin.size() == 1) {
            setSelectedOrganisationPerson(organisationsToAdmin.get(0));
        }
    }

    public String setUserMode() {
        systemMode = SystemMode.USER;
        theme = "blue";
        setSelectedOrganisationPerson(null);
        return "/app/dashboard?faces-redirect=true";
    }

    public String setAdminMode() {
        systemMode = SystemMode.ADMIN;
        theme = "red";
        if (organisationsToAdmin .size() > 0) {
            setSelectedOrganisationPerson(organisationsToAdmin.get(0));
        }
        return "/app/dashboard?faces-redirect=true";
    }

    public String setSysAdminMode() {
        systemMode = SystemMode.SYSADMIN;
        theme = "red";
        setSelectedOrganisationPerson(null);
        return "/app/dashboard?faces-redirect=true";
    }

    public boolean isUserMode() {
        return systemMode.equals(SystemMode.USER);
    }

    public boolean isAdminMode() {
        return systemMode.equals(SystemMode.ADMIN);
    }

    public boolean isSystemAdminMode() {
        return systemMode.equals(SystemMode.SYSADMIN);
    }
    
    public boolean canSwitchToAdmin() {
        return adminAllowed && !isAdminMode();
    }
    
    public boolean canSwitchToSystemAdmin() {
        return systemAdminAllowed && !isSystemAdminMode();
    }

    public String getTheme() {
        return theme;
    }

    public void setTheme(String theme) {
        this.theme = theme;
    }

    public String getSystemMode() {
        return systemMode.value();
    }

    public boolean isSystemAdminAllowed() {
        return systemAdminAllowed;
    }

    public void setSystemAdminAllowed(boolean systemAdminAllowed) {
        this.systemAdminAllowed = systemAdminAllowed;
    }

    public boolean isAdminAllowed() {
        return adminAllowed;
    }

    public void setAdminAllowed(boolean adminAllowed) {
        this.adminAllowed = adminAllowed;
    }

    public List<OrganisationMembership> getOrganisationsToAdmin() {
        return organisationsToAdmin;
    }

    public void setOrganisationsToAdmin(List<OrganisationMembership> organisationsToAdmin) {
        this.organisationsToAdmin = organisationsToAdmin;
    }

    public OrganisationMembership getSelectedOrganisationPerson() {
        return selectedOrganisationPerson;
    }

    public void setSelectedOrganisationPerson(OrganisationMembership  selectedOrganisationPerson) {
        this.selectedOrganisationPerson = selectedOrganisationPerson;
    }

    /**
     * Get a list of clubs the person is an administrator of.
     *
     * @param person the person to get the list of organisations for
     * @return a list of organisationPersonTO that the person can administer.
     */
    private List<OrganisationMembership> getOrganisationsToAdmin(Person person) {
        organisationsToAdmin = person.getMemberships().stream()
                .filter(organisationPerson -> organisationPerson.getOrganisationRoles().equals(OrganisationRole.ADMINISTRATOR))
                .collect(Collectors.toList());
        return organisationsToAdmin;
    }

    public String switchOrganisation() {
        return "/app/dashboard?faces-redirect=true";
    }
}

EquissentialHorses/web/WEB-INF/footer.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">
    
    <div class="footer">
        <h:graphicImage id="footer-logo" name="images/equissential.png" style="height:50px"/>
        <p>Equissential</p>
        
        <div class="copyright">
            <p>All rights reserved.</p>
        </div>
    </div>
    
</ui:composition>

EquissentialHorses/web/WEB-INF/layoutmenu.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:pi="http://primefaces.org/icarus">


    <h:form id="menuform"> 

        <pi:menu widgetVar="IcarusMenu" rendered="#{systemBean.userMode}">
            <p:menuitem id="im_dashboard" value="Dashboard" icon="fa fa-home" outcome="/app/dashboard"/>
            <p:menuitem id="im_db_landing" value="Promotion Page" icon="fa fa-certificate" outcome="/app/dashboard"/>
            <p:submenu id="im_components" label="Components" icon="fa fa-sitemap">
                <p:menuitem id="im_sample" value="Sample Page" icon="fa fa-columns" outcome="/app/dashboard" />
                <p:menuitem id="im_forms" value="Forms" icon="fa fa-code" outcome="/app/dashboard" />
                <p:menuitem id="im_data" value="Data" icon="fa fa-table" outcome="/app/dashboard" />
                <p:menuitem id="im_panels" value="Panels" icon="fa fa-list-alt" outcome="/app/dashboard" />
                <p:menuitem id="im_overlays" value="Overlays" icon="fa fa-square" outcome="/app/dashboard" />
                <p:menuitem id="im_menus" value="Menus" icon="fa fa-minus-square-o" outcome="/app/dashboard" />
                <p:menuitem id="im_messages" value="Messages" icon="fa fa-circle-o-notch" outcome="/app/dashboard" />
                <p:menuitem id="im_charts" value="Charts" icon="fa fa-area-chart" outcome="/app/dashboard" />
                <p:menuitem id="im_fileupload" value="FileUpload" icon="fa fa-arrow-circle-o-up" outcome="/app/dashboard" />
                <p:menuitem id="im_misc" value="Misc" icon="fa fa-user-secret" outcome="/app/dashboard" />
            </p:submenu>
            <p:submenu id="im_default" label="Default Pages" icon="fa fa-life-saver">
            </p:submenu>
            <p:submenu id="im_hierarchy" label="Menu Hierarchy" icon="fa fa-gg">
                <p:submenu id="im_sm1" label="Submenu 1" icon="fa fa-sign-in">
                    <p:submenu id="im_sm11" label="Submenu 1.1" icon="fa fa-sign-in">
                        <p:submenu id="im_sm111" label="Submenu 1.1.1" icon="fa fa-sign-in">
                            <p:menuitem id="im_lnk1111" value="Link 1" icon="fa fa-sign-in" url="#" />
                            <p:menuitem id="im_lnk1112" value="Link 2" icon="fa fa-sign-in" url="#" />
                            <p:menuitem id="im_lnk1113" value="Link 3" icon="fa fa-sign-in" url="#" />
                        </p:submenu>
                    </p:submenu>
                    <p:menuitem id="im_lnk12" value="Submenu 1.2" icon="fa fa-sign-in" url="#" />
                    <p:menuitem id="im_lnk13" value="Submenu 1.3" icon="fa fa-sign-in" url="#" />
                </p:submenu>
                <p:submenu id="im_sm2" label="Submenu 2" icon="fa fa-sign-in">
                    <p:submenu id="im_21" label="Submenu 2.1" icon="fa fa-sign-in">
                        <p:submenu id="im_211" label="Submenu 2.1.1" icon="fa fa-sign-in">
                            <p:menuitem id="im_lnk2111" value="Link 1" icon="fa fa-sign-in" url="#" />
                            <p:menuitem id="im_lnk2112" value="Link 2" icon="fa fa-sign-in" url="#" />
                            <p:menuitem id="im_lnk2113" value="Link 3" icon="fa fa-sign-in" url="#" />
                        </p:submenu>
                    </p:submenu>
                </p:submenu>
            </p:submenu>
            
        </pi:menu>

        <pi:menu widgetVar="IcarusMenu2" rendered="#{systemBean.adminMode}">
            <p:menuitem id="im_admin_dashboard" value="Admin" icon="fa fa-home" outcome="/app/dashboard"/>
            <p:submenu id="im_admin_tasks" label="#{bundle['tasks']}" icon="fa fa-list">
                <p:menuitem id="im_admin_join_request" value="#{bundle['joinRequests']}" outcome="/app/admin/pendingJoinRequests" />
            </p:submenu>
            <p:submenu id="im_admin_settings" label="#{bundle['settings']}" icon="fa fa-cog">
                <p:menuitem id="im_admin_media" value="#{bundle['media']}" outcome="/app/admin/media" />
                <p:menuitem id="im_admin_categories" value="#{bundle['categories']}" outcome="/app/admin/category" />
                <p:menuitem id="im_admin_awards" value="#{bundle['awards']}" outcome="/app/admin/award" />
                <p:menuitem id="im_admin_ratings" value="#{bundle['ratings']}" outcome="/app/admin/rating" />
                <p:menuitem id="im_admin_promo_criteria" value="#{bundle['promotionCriteria']}" outcome="/app/admin/promotionCriteriaList" />
            </p:submenu>
            
        </pi:menu>
        
        <pi:menu widgetVar="IcarusMenu3" rendered="#{systemBean.systemAdminMode}">
            <p:menuitem id="im_sys_admin_dashboard" value="System Admin" icon="fa fa-home" outcome="/app/dashboard"/>
            <p:submenu id="im_sys_admin_todo" label="To Do" icon="fa fa-sitemap">
                <p:menuitem id="im_sys_admin_join_request" value="#{bundle['joinRequests']}" icon="fa fa-user" outcome="/app/dashboard" />
            </p:submenu>
            
        </pi:menu> 
    </h:form>
    
</ui:composition>

EquissentialHorses/web/WEB-INF/sidebarheader.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">
    

    <div id="sidebar-header">
        <div id="logo-wrapper">
            <h:graphicImage name="images/equissential.png" id="logo" width="76"/>
        </div>
        <a id="slim-menu-button" href="#">
            <i class="fa fa-bars" aria-hidden="true"></i>
        </a>
    </div>

    
</ui:composition>

EquissentialHorses/web/WEB-INF/template.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <f:facet name="first">
            <meta http-equiv="X-UA-Compatible" content="IE=edge" />
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
            <meta name="apple-mobile-web-app-capable" content="yes" />
        </f:facet>
        <title>Equissential</title>
        <h:outputScript name="js/nanoscroller.js" library="icarus-layout" />
        <h:outputScript name="js/layout.js" library="icarus-layout" />
        <h:outputScript library="js" name="emma.js" />        

        <ui:insert name="head"/>
    </h:head>

    <h:body>
        <div class="wrapper">

            <div id="sidebar-wrapper">
                <ui:include src="sidebarheader.xhtml" />

                <div class="sidebar-nav nano">
                    <div class="nano-content sidebar-scroll-content">
                        <ui:include src="layoutmenu.xhtml" />
                    </div>
                </div>
            </div>   

            <ui:include src="topbar.xhtml" />         

            <div id="main-wrapper">
                <div class="main-content">
                    <ui:insert name="content"></ui:insert>
                </div>

                <ui:include src="footer.xhtml" />
            </div>
        </div>

        <p:ajaxStatus style="width:32px;height:32px;position:fixed;right:7px;bottom:7px">
            <f:facet name="start">
                <p:graphicImage name="images/preloader.gif" library="icarus-layout" style="width: 32px;"/>
            </f:facet>

            <f:facet name="complete">
                <h:outputText value="" />
            </f:facet>
        </p:ajaxStatus>

        <h:outputStylesheet name="css/animate.css" library="icarus-layout" />
        <h:outputStylesheet name="css/nanoscroller.css" library="icarus-layout" />
        <h:outputStylesheet name="css/layout-#{systemBean.theme}.css" library="icarus-layout" />

    </h:body>

    <p:ajaxExceptionHandler type="za.co.cf.emma.web.beans.ClientException"
                            update="exceptionDialog" onexception="PF('exceptionDialog').show();" />
    <p:dialog id="exceptionDialog" header="" widgetVar="exceptionDialog" modal="true" responsive="true">
        <h:outputText value="#{pfExceptionHandler.message}" escape="false" />        
        <br/><br/>
        <p:button onclick="document.location.href = document.location.href;" value="Close"/>
    </p:dialog>    

</html>

EquissentialHorses/web/WEB-INF/topbar.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

    <h:panelGroup layout="block" id="top-bar-wrapper">
        <div id="top-bar">
            <div class="search-bar">
                <p:outputLabel value="#{systemBean.selectedOrganisationPerson.organisation.name}" styleClass="search"/>
            </div>

            <div class="top-bar-profile">
                <div class="profile-name">
                    <span><h:outputText value="#{person.firstName} #{person.surname} "/></span><br/>
                    <h:outputText value="#{systemBean.systemMode}" rendered="#{!systemBean.userMode}"/>
                </div>
                <a href="#" id="profile-image">
                    <h:graphicImage name="images/profile.png" library="icarus-layout" style="border: 0 none;"/>
                </a>
                <ul class="top-submenu animated flipInX">
                    <li>
                        <h:form id="myProfileFrm">
                            <h:commandLink id="myProfile" action="/app/profile">
                                <i class="fa fa-fw fa-user"></i>
                                <span><h:outputText value="#{bundle['profile']}"/></span>
                            </h:commandLink>
                        </h:form>
                    </li>
                    <li>
                        <h:form id="joinOrgFrm">
                            <h:commandLink id="joinOrg" action="/app/joinOrganisation">
                                <i class="fa fa-fw fa-users"></i>
                                <span><h:outputText value="#{bundle['joinOrganisation']}"/></span>
                            </h:commandLink>
                        </h:form>
                    </li>
                    <li>
                        <a href="#">
                            <i class="top-submenu-icon fa fa-fw fa-envelope"></i>
                            <span>Messages</span>
                            <span class="top-submenu-badge">5</span>
                        </a>
                    </li>

                    <li>
                        <h:form id="userModeForm">
                            <h:commandLink id="userMode" action="#{systemBean.setUserMode()}" rendered="#{!systemBean.userMode}">
                                <i class="fa fa-fw fa-camera"></i>
                                <span><h:outputText value="#{bundle['userMode']}"/></span>
                            </h:commandLink>
                        </h:form>
                    </li>
                    <li>
                        <h:form id="adminModeForm">
                            <h:commandLink id="adminMode" action="#{systemBean.setAdminMode()}" rendered="#{systemBean.canSwitchToAdmin()}">
                                <i class="top-submenu-icon fa fa-fw fa-cogs"></i>&#160;<h:outputText value="#{bundle['adminMode']}"/>
                            </h:commandLink>
                        </h:form>
                    </li>
                    <li>
                        <h:form id="sysAdminModeForm">
                            <h:commandLink id="systemAdminMode" action="#{systemBean.setSysAdminMode()}" rendered="#{systemBean.canSwitchToSystemAdmin()}">
                                <i class="top-submenu-icon fa fa-fw fa-wrench"></i>&#160;<h:outputText value="#{bundle['systemAdminMode']}"/>
                            </h:commandLink>
                        </h:form>
                    </li>                    
                    <li>
                        <h:form id="topBarSwitchOrgForm">
                            <h:commandLink id="topBarSwitchOrgLink" action="/app/admin/switchOrganisation" rendered="#{systemBean.adminMode}">
                                <i class="top-submenu-icon fa fa-fw fa-exchange"></i>&#160;<h:outputText value="#{bundle['switchOrganisation']}"/>
                            </h:commandLink>
                        </h:form>
                    </li>
                    <li>
                        <h:form>
                            <h:commandLink id="logout" action="#{loginBean.logout}">
                                <i class="top-submenu-icon fa fa-fw fa-close"></i>&#160;<h:outputText value="#{bundle['logout']}"/>
                            </h:commandLink>
                        </h:form>
                    </li>
                </ul>
            </div>

            <div id="top-menu" class="top-menu">
                <div class="top-bar-icon">
                    <a href="#">
                        <i class="fa fa-bell-o animated swing" aria-hidden="true"></i>
                        <i class="top-bar-badge animated rubberBand">3</i>
                    </a>
                    <ul class="top-submenu animated flipInX">
                        <li class="header">You have 3 tasks.</li>
                        <li>
                            <a href="#">
                                <i class="top-submenu-icon fa fa-fw fa-mobile"></i>
                                <span>Mobile app release</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="top-submenu-icon fa fa-fw fa-line-chart"></i>
                                <span>Review sale reports</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="top-submenu-icon fa fa-fw fa-plane"></i>
                                <span>Reserve flight</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="top-bar-icon">
                    <a href="#">
                        <i class="fa fa-envelope-o animated swing" aria-hidden="true"></i>
                        <i class="top-bar-badge animated rubberBand">5</i>
                    </a>
                    <ul class="top-submenu animated flipInX">
                        <li class="header">You have 5 messages.</li>
                        <li>
                            <a href="#">
                                <p:graphicImage name="images/avatar_1.png" library="icarus-layout" width="35"/>
                                <span>Nice to meet you.</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <p:graphicImage name="images/avatar_2.png" library="icarus-layout" width="35"/>
                                <span>Sales reports attached.</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <p:graphicImage name="images/avatar_3.png" library="icarus-layout" width="35"/>
                                <span>About your invoice.</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <p:graphicImage name="images/avatar_4.png" library="icarus-layout" width="35"/>
                                <span>Meeting today at 10pm.</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <p:graphicImage name="images/avatar_2.png" library="icarus-layout" width="35"/>
                                <span>Lunch today?</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </h:panelGroup>
</ui:composition>